### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by CebollaMan** [AkkilMG/MoE-Bot#1]
The login process fails with the following error:

Analysis of the Code:
```
------------------- MoE-Bot -------------------
----------------------- Service Started -----------------------

DevTools listening on ws://127.0.0.1:52900/devtools/browser/aaaeda43-93ec-491b-8885-99651f9199bb
Login page detected
Exception occurred: list index out of range
Login failed
```

The error happens consistently, even after trying different devices, resetting the password, and testing with multiple accounts. Despite detecting the login page, the error "list index out of range" occurs when trying to process the login credentials.
Analysis of the Code:

The login() function seems to properly navigate to the login page, waits for the necessary elements (mail and p for email and password) to load, and interacts with them using Selenium.
The selectors in the login function appear correct, as the page source confirms the names for the input fields (mail and p).
The issue seems to occur after filling in the login form but before completing the login process.
    
I cannot scratch my head of what´s happening. Maybe cand you help me get a fix?

**Comment by AkkilMG** [comment]
We will check it out

**Comment by AkkilMG** [comment]
Dear @CebollaMan,
I have tested it multiple time, it still worked for me. The current version handles MoE work in dictator or monarchy based governance only. I will release the newer version which will be for presidential or one party system based governance.
If you could share me a video of it, when it happens. Or give me more details, I would be able to help you out.

**Note**: Try using virtual environment. Command is follows
```bash
python -m venv moe
```
To activate use below command in the powershell
```bash
./moe/Scripts/Activate.ps
```


Thank you

**Comment by CebollaMan** [comment]
![imagen](https://github.com/user-attachments/assets/f85c6892-d41a-479a-985b-04be8d3100a1)

I isolated the environment in python and didn´t work. But yeah, the problem could be that I´m triying to do it in a Republic.

This is the account if you wanted to check: https://rivalregions.com/#slide/profile/2001607321

And my tg in case I could be in any assist: https://t.me/Cebolla_Man

**Comment by AkkilMG** [comment]
Oh sorry, will iterate a new update for republic.

**Comment by AkkilMG** [comment]
Dear @CebollaMan,

The code has been updated for **Republic** also. If any issue, contact on telegram and let me know.
Thank you
